# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e73ac8e163c8bd8ddf0f001197d996b2cf6747db01bba44507f8567dc697d0f713a6c24c04c205dadc725a8af08c1e921794adfdae8fc841ca3d6e2b5c81035

test:
  secret_key_base: 4fa2e9241db8d14a4ce7ffcc9019c9ff7fbee81444c0a360b07d4d3c255dad3d585dad2360bb991c299bd7e7e643b7c45778690fa6211b741a62b1f4b35423b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
